spring:
 datasource:
#  hikari:
   url: jdbc:mysql://34.131.133.36:3306/hospital_management?useUnicode=true&characterEncoding=utf8
   username: root
   password: 1234
   driver-class-name: com.mysql.jdbc.Driver
spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql: true
spring.jpa.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.generate-ddl: false
#spring.jpa.hibernate.ddl-auto: none
lower_case_table_names: 0
spring.datasource.testWhileIdle: true
spring.datasource.test-on-borrow: true
#   driver-class-name: oracle.jdbc.OracleDriver
#   connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
#   minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
#   maximum-pool-size: 10 #maximum pool size
#   idle-timeout: 10000 #maximum idle time for connection
#   max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
#   auto-commit: true #default auto-commit behavior.
#spring.jpa.database-platform: org.hibernate.dialect.Oracle12cDialect
#spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: DEBUG
logging.level.com.zaxxer.hikari.HikariConfig: DEBUG
logging.level.org.hibernate.SQL: DEBUG
#server:
#  port: 8081